language: node_js
node_js:
  - "0.11"
  - "0.10"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.travis.json config/database.json
  - psql -c 'create database resourceperf_test;' -U postgres